sudo: required

services:
  - docker

python:
  - '2.7'

env:
  matrix:
  - TOX_ENV=flake8

install:
  - pip install .
  - pip install -r test-requirements.txt

script:
  - tox -e $TOX_ENV
  - pip list --format=columns | grep pyvcloud
  - vca --version
  - vcd version
