sudo: false
language: python
python:
- '2.7'
env:
  matrix:
  - TOX_ENV=flake8
  global:
  - secure: LDmQYElpq2TULNXbrhOuGZCfZWsftcOI6mj3ucewGySVeaW2vItuT4WjwGjbsJmECcJ0tNJrybXIrW6VmwvvWceAgzgCOfGgh3Xd5ksgkx7jjScPyTdzYkVL5uuH5OQqGF+ZIa+sPzelye3imkLrR+bNvg+2ef8TFnGn+egp3Hw=
  - secure: SEbxyHgWm9DPnM0ZhS9wKVwGIWcwLqhZ7KzBhk3vT4vr3Ks2RlBzjlA+vFHzCjIBIMVAIISYelb8DNRF9Ennb9HbBkShB1HYg8ZmLsMPtGOQjLpv9NwCSRZ0Q5lyuaXMIyenWUn+R/UaYgs38aQ65zRbeyuVIru2+QgVpM5tho8=
  - secure: jc2gxWvNai+yQenobsHFnreAHwoc4DFVxHMjQFrhuD2rTgGCTkw4jiEtObqq8yC+DCpKM37Q5h0M+qwFElTEoHBfze1qWW8XUgVj/TgKtjeusHVM1vExclYxy1LmkZ/Aaw4gjP3S/Q9kIZow1zJqU5Ld++E17Vp7w/MM8JQMxa0=
install:
- pip install -r requirements.txt
- pip install tox
script:
- tox -e $TOX_ENV
- pip install .
- tests/login-vca.sh
